version: '3.8'

services:
  backend:
    build: ./backend
    container_name: terraguard-api
    ports:
      - "8000:8000"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend:/app
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - terraguard-network

  frontend:
    build: ./frontend
    container_name: terraguard-ui
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - terraguard-network

networks:
  terraguard-network:
    driver: bridge